#!/usr/bin/env bash

DATADIR=${DATADIR:-/var/lib/fath2boinc}
BOINCSTATSDIR=${BOINCSTATSDIR:-/usr/share/nginx/html}

curl -fsSL https://apps.foldingathome.org/daily_user_summary.txt.bz2 | bunzip2 > daily_user_summary.txt
fath2boinc "$DATADIR/users.csv" daily_user_summary.txt "$BOINCSTATSDIR/user"
rm daily_user_summary.txt
gzip "$BOINCSTATSDIR/user"
