#!/usr/bin/env bash

DATADIR=${DATADIR:-/var/lib/fath2boinc}
BOINCSTATSDIR=${BOINCSTATSDIR:-/usr/share/nginx/html}

mkdir -p "$DATADIR"
mkdir -p "$BOINCSTATSDIR"

curl -fsSL https://apps.foldingathome.org/daily_user_summary.txt.bz2 | bunzip2 > "$DATADIR/daily_user_summary.txt"
fath2boinc "$DATADIR/users.csv" "$DATADIR/daily_user_summary.txt" "$BOINCSTATSDIR/user"
rm -f "$BOINCSTATSDIR/user.gz~"
gzip -S ".gz~" "$BOINCSTATSDIR/user"
mv "$BOINCSTATSDIR/user.gz~" "$BOINCSTATSDIR/user.gz"
